
version: '3.4'

networks:
  ebw-movies-ntk:
    driver: bridge 

services:
  ebw-movies-api:
    image: ebw-movies-api:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=ebw-movies;username=ebw-user;password=ebw-user"
    networks:
      - ebw-movies-ntk  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "ebw-user"
      POSTGRES_PASSWORD: "ebw-user"
      POSTGRES_DB: "ebw-movies"
    networks:
      - ebw-movies-ntk
volumes:
  db_volume:
         
    