
version: '3.4'

services:
  ebw-mq-api:
    image: yareddej/ebw-mq:latest
    depends_on:
      - "postgres_image"
    ports:
      - "8000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=ebw-movies;username=ebw-user;password=ebw-user"
      KUBE_MQ_CLUSTER: "127.0.0.1:50000"
    network_mode: host
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./app/dbscripts:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "ebw-user"
      POSTGRES_PASSWORD: "ebw-user"
      POSTGRES_DB: "ebw-movies"
    network_mode: host

volumes:
  db_volume:
         
    