apiVersion: v1
kind: Service
metadata:
  name: ebw-mq
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: ebw-mq